# Generated by Django 3.1.2 on 2021-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('transgender', 'TRANSGENDER')], default='male', max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
